name: OSS OPlus SM8650 Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config --global user.name "AzusaHana"
        git config --global user.email "chenyue2330@gmail.com"

    - name: Clean up disk space
      run: |
        sudo apt-get clean
        sudo rm -rf /usr/share/dotnet /etc/mysql /var/lib/mysql
        sudo rm -rf /usr/local/lib/android
        df -h

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 git curl

    - name: Install repo tool
      run: |
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
        chmod a+x ~/repo
        sudo mv ~/repo /usr/local/bin/repo

    - name: Initialize repo and sync
      run: |
        mkdir kernel_workspace && cd kernel_workspace
        repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b refs/heads/oneplus/sm8650 -m oneplus12_v.xml --depth=1
        repo sync

    - name: Setup KernelSU
      run: |
        cd $GITHUB_WORKSPACE
        git clone https://github.com/tiann/KernelSU
        cd kernel_workspace/kernel_platform
        GKI_ROOT=$(pwd)
        ln -sf $GITHUB_WORKSPACE/KernelSU/kernel $GKI_ROOT/common/drivers/kernelsu
        DRIVER_MAKEFILE=$GKI_ROOT/common/drivers/Makefile
        DRIVER_KCONFIG=$GKI_ROOT/common/drivers/Kconfig
        grep -q "kernelsu" "$DRIVER_MAKEFILE" || printf "\nobj-\$(CONFIG_KSU) += kernelsu/\n" >> "$DRIVER_MAKEFILE"
        grep -q "kernelsu" "$DRIVER_KCONFIG" || sed -i "/endmenu/i\\source \"drivers/kernelsu/Kconfig\"" "$DRIVER_KCONFIG"
        if [ ! -e build/build.sh ]; then
          GLIBC_VERSION=$(ldd --version 2>/dev/null | head -n 1 | awk '{print $NF}')
          echo "GLIBC_VERSION: $GLIBC_VERSION"
          if [ "$(printf '%s\n' "2.38" "$GLIBC_VERSION" | sort -V | head -n1)" = "2.38" ]; then
            echo "Patching resolve_btfids/Makefile"
            cd $GKI_ROOT/common/ && sed -i '/\$(Q)\$(MAKE) -C \$(SUBCMD_SRC) OUTPUT=\$(abspath \$(dir \$@))\/ \$(abspath \$@)/s//$(Q)$(MAKE) -C $(SUBCMD_SRC) EXTRA_CFLAGS="$(CFLAGS)" OUTPUT=$(abspath $(dir $@))\/ $(abspath $@)/' tools/bpf/resolve_btfids/Makefile || echo "No patch needed."
          fi
        fi
        repo status
        
    - name: Make working directory clean to avoid dirty
      run: |
        cd kernel_workspace/kernel_platform/common
        rm android/abi_gki_protected_exports_* || echo "No protected exports!"
        git add -A && git commit -a -m "Add KernelSU"
        repo status

    - name: Build kernel
      run: |
        cd kernel_workspace
        ./kernel_platform/oplus/build/oplus_build_kernel.sh pineapple gki

    - name: Make AnyKernel3
      run: |
        git clone https://github.com/Kernel-SU/AnyKernel3 --depth=1
        rm -rf ./AnyKernel3/.git
        cp kernel_workspace/kernel_platform/out/msm-kernel-pineapple-gki/dist/Image ./AnyKernel3/

    - name: Upload AnyKernel3
      uses: actions/upload-artifact@v4
      with:
        name: AnyKernel3-OSS-OPlus12-V
        path: ./AnyKernel3/*

    - name: Upload kernel Image
      uses: actions/upload-artifact@v4
      with:
        name: Image-OSS-OPlus12-V
        path: kernel_workspace/kernel_platform/out/msm-kernel-pineapple-gki/dist/Image

    - name: Upload boot.img
      uses: actions/upload-artifact@v4
      with:
        name: boot-OSS-OPlus12-V.img
        path: kernel_workspace/kernel_platform/out/msm-kernel-pineapple-gki/dist/boot.img
